### PR TITLE
AttributeDuplicateFilter

### PR DESCRIPTION
**Pull request by jashanbhullar**
# Overview
Detects duplicate features based on the value of one or more key attributes. 
The input is expected to be of `ActionValue::Map` with `Map` containing `keys and values` 

## What I've done
- Implementation
- Unit Test

## What I haven't done
- Tested in Workflow 
- Integration test

## How I tested
- NA

## Screenshot
- NA

## Which point I want you to review particularly
- Since it's my first PR I would request slightly thorough feedback
- The core functionality
- The Unit Test
- Integration test
- Workflow test

## Memo
- NA

### CODE REVIEW

**Comment by miseyu** [comment]
@jashanbhullar 
I hope you can change the name of the latest Action 🙇

**Review by miseyu — APPROVED** [review]
LGTM

**Comment by jashanbhullar** [comment]
@miseyu can i merge this?

**Comment by miseyu** [comment]
> @miseyu can i merge this?
OK!

**Comment by jashanbhullar** [comment]
@miseyu can I merge this then?

**Pull request merged**
